apiVersion: v1
kind: Namespace
metadata:
  name: amrit-gill
---
apiVersion: "amritgill.alpha.coveros.com/v1alpha1"
kind: "S3"
metadata:
  name: s3
  namespace: amrit-gill
s3Specs:
  bucketName: iksjgudamritcsdsdgasidgasiksdc
  # syncWith: 
  #   s3Bucket: copyFromBucket
  region: us-east-1
