apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deletenses.amritgill.alpha.coveros.com
spec:
  group: amritgill.alpha.coveros.com
  names:
    kind: DeleteNs
    listKind: DeleteNsList
    plural: deletenses
    singular: deletens
  scope: Namespaced
  version: v1alpha1
